<a href="https://colab.research.google.com/github/anvq38/CS114.K21.KHTN/blob/master/KNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import neighbors, datasets

In [15]:
iris = datasets.load_iris()
iris_X = iris.data
iris_Y = iris.target

print('Number of classes: %d' %len(np.unique(iris_Y)))
print('Number of data points: %d' %len(iris_Y))


X0 = iris_X[iris_Y == 0,:]
print('\n Samples from class 0: \n', X0[:5, :])

X1 = iris_X[iris_Y == 1, :]
print('\n Samples from class 1: \n', X1[:5, :])

X2 = iris_X[iris_Y == 2, :]
print('\n Samples from class 2: \n', X2[:5, :])

Number of classes: 3
Number of data points: 150

 Samples from class 0: 
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

 Samples from class 1: 
 [[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]

 Samples from class 2: 
 [[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]


In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(iris_X, iris_Y, test_size = 50)

print('Training size: %d' %len(Y_train))
print('Test size: %d' %len(Y_test))

Training size: 100
Test size: 50


In [34]:
clf = neighbors.KNeighborsClassifier(n_neighbors=1, p = 2)
clf.fit(X_train, Y_train)
Y_pred = clf.predict(X_test)

print ("Print results for 20 test data points:")
print ("Predicted labels: ", Y_pred[20:40])
print ("Ground truth    : ", Y_test[20:40])

Print results for 20 test data points:
Predicted labels:  [2 1 0 0 0 1 2 2 1 2 2 2 0 2 2 1 1 1 1 0]
Ground truth    :  [2 1 0 0 0 1 2 2 1 2 2 2 0 1 2 1 1 1 1 0]


In [35]:
from sklearn.metrics import accuracy_score
print("Accuracy of 1NN: %2.f %%" %(100 * accuracy_score(Y_test, Y_pred)))

Accuracy of 1NN: 98 %


In [36]:
clf = neighbors.KNeighborsClassifier(n_neighbors=10, p = 2)
clf.fit(X_train, Y_train)
Y_pred = clf.predict(X_test)
accuracy_score(Y_test, Y_pred)

0.96

In [37]:
clf = neighbors.KNeighborsClassifier(n_neighbors=10, p = 2, weights = 'distance')
clf.fit(X_train, Y_train)
Y_pred = clf.predict(X_test)
accuracy_score(Y_test, Y_pred)

0.98